### ISSUE TITLE
Error CS8103 after upgrading from 4.18.0 to 5.x.x

### ISSUE THREAD

**Issue by victorolawale** [microsoftgraph/msgraph-sdk-dotnet#2163]
I recently upgraded from 4.18.0 to any of the versions 5.x.x. I have been getting Error CS8103 while building my project.

<img width="441" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/1159462/5a7aa75a-6db1-444f-9cce-0c5c180ad828">

I wanted to be sure of the problem so I downgraded to version 4.54.0 and the project was able to build.
<img width="677" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/1159462/09b4d287-d896-45c2-93da-751d2ae2c10e">

I have also read the [guide ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md) on upgrading to v5. There seems to be nothing that points to this compile time error.

In addition, I have also tried to search online on a work around that is relevant to my use case, nothing seems to solve the issue. However, I am very sure the problem was from the v5.x.x of the Microsoft.Graph Sdk.

**Error CS8103: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.**

Please help as I am currently blocked.

**Comment by bgreen77** [comment]
Yes.  Having the same problem here as well.

Using Microsoft.Graph in an internal library that is used in an Orleans Grain (targeting netstandard2.0 and net7.0) to create users in Azure B2C.

Today, I upgraded this to the latest version (Microsoft.Graph version 5.36.0) and started seeing the same error above:

> CS8103 - Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.

Only removing this reference (even if it's transitive) from the project containing the grains does this error resolve.

**Actually.....**

I did some testing, and managed to determine that:
- This issue occurs with Microsoft.Graph version 5.36.0
- This issue does not occur with Microsoft.Graph versions 5.35.0 or lower (*)

(*) I testing a few versions, jumping around looking for the first version that the error occurred.  I can confidently say that 5.0.0, 5.20.0, 5.30.0, 5.33.0, 5.34.0 and 5.35.0 do not have this issue.

**Comment by bgreen77** [comment]
Yes. Having the same problem here as well.

Using Microsoft.Graph in an internal library that is used in an Orleans Grain (targeting `netstandard2.0` and `net7.0`) to create users in Azure B2C.

Today, I upgraded this to the latest version (`Microsoft.Graph` version `5.36.0`) and started seeing the same error above:

> CS8103 - Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.

Only removing this reference (even if it's transitive) from the project containing the grains does this error resolve.

**Actually.....**

I did some testing, and managed to determine that:
- This issue occurs with `Microsoft.Graph` version `5.36.0`
- This issue does not occur with `Microsoft.Graph` versions `4.54.0`

So I, too, have rolled back. But it'd be nice to see the latest version of the library usable from Orleans.

**Comment by ilanhu** [comment]
Same here.
Getting the same error 
`error CS8103: Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals.`
while using `<PackageReference Update="Microsoft.Graph" Version="5.41.0" />`

Is there a plan fix for this issue?

**Comment by victorolawale** [comment]
I think this issue only happens on any project targeting below .NET7.0.

I upgraded the project to NET8.0 and also have the SDK upgraded. It works and resolves the issue.

**Comment by evanweissms** [comment]
Hi @andrueastman is there any update on this? We're also blocked on this issue and are unable to upgrade to NET8.0 as a potential mitigation

**Comment by ctcLeonard** [comment]
Any update on this bug? I am in the same boat as various above commenters. Using Orleans with .net7.0. Upgrading to .net8.0 doesn't seem to fix the issue for me it still throws the same exception.
