### ISSUE TITLE
.NET 4.6.1 class library referencing Microsoft.Graph.Core strange behavior 

### ISSUE THREAD

**Issue by rychlym** [microsoftgraph/msgraph-sdk-dotnet#195]
Hello,
I understand the Microsoft.Graph.Core is build against .NET Standard. I am not so familiar with the .NET Standard, I am not sure it is a bug or a  feature, that when the Microsoft.Graph.Core is referenced from a classic  class library targeted to .NET 4.6.1 (reference created in through Nuget without any problems),
then there appears compilation errors, like there is needed that referenced library? 

in detail e.g compilation error like: 
The type 'IBaseRequest' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Graph.Core, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null'.

meanwhile the reference in the project seems to be valid!

another aka .net standard question:
In the Readme.Md is written that "The Microsoft Graph .NET Client Library targets .NetStandard 1.1 and .Net Framework 4.5"
Sorry again, I am quite confused with that - does it mean, that I must not use that in .NET projects that uses .NET higher target framework, than 4.5?

**Comment by filipliwinski** [comment]
Same problem with my project (.NET 4.5.2) after updating Microsoft.Graph to 1.6.1 and Microsoft.Graph.Core to 1.6.2.

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention. I'm looking into this now

**Comment by MIchaelMainer** [comment]
Okay, this should now be fixed. Can you install version 1.6.2

Install-Package Microsoft.Graph -Version 1.6.2

It now has a reference to Microsoft.Graph.Core with the public key in the Microsoft.Graph in the assembly manifest. Can you confirm that it works as expected?

**Comment by rychlym** [comment]
Hi,
great, I can confirm, that this issue is solved by installing the new Microsoft.Graph -Version 1.6.2.

**Comment by MIchaelMainer** [comment]
Thank you for confirming this.

**Comment by rychlym** [comment]
Not at all. Just a complementary question, I tried to look to your change in the source code inside to this issue, bat without success (looked in the master and the dev branches). It seems not to be public, is it?

**Comment by MIchaelMainer** [comment]
I just pushed it to GH.
