### ISSUE TITLE
[Client bug]: v5 PageIterator is broken

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-dotnet#1676]
**Describe the bug**
There are two extensions 

`public static PageIterator<TEntity, TCollectionPage> CreatePageIterator(IBaseClient client, TCollectionPage page, Func<TEntity, bool> callback, Func<RequestInformation, RequestInformation> requestConfigurator = null)`

`public static PageIterator<TEntity, TCollectionPage> CreatePageIterator(IBaseClient client, TCollectionPage page, Func<TEntity, Task<bool>> asyncCallback, Func<RequestInformation, RequestInformation> requestConfigurator = null)`

When I use the first variant in code

```
var pageIterator = PageIterator<Message, MessageCollectionResponse>.CreatePageIterator(_client, messagesResponse, (message) =>
                {
                    ...
                    return true;
                });
```

I get compile error

```
error CS0029: Cannot implicitly convert type 'bool' to 'System.Threading.Tasks.Task<bool>'
error CS1662: Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type
```

When I use the second variant

```
var pageIterator = PageIterator<Message, MessageCollectionResponse>.CreatePageIterator(_client, messagesResponse, async (message) =>
                {
                    await Task.CompletedTask;
                    return true;
                });
```

I get another compile error

`error CS4010: Cannot convert async lambda expression to delegate type 'Func<Message, bool>'. An async lambda expression may return void, Task or Task<T>, none of which are convertible to 'Func<Message, bool>'`

As a result I'm not able to use PageIterator

**To Reproduce**
use `public static PageIterator<TEntity, TCollectionPage> CreatePageIterator(IBaseClient client, TCollectionPage page, Func<TEntity, bool> callback, Func<RequestInformation, RequestInformation> requestConfigurator = null)`

**Expected behavior**
No compile error

**Screenshots**

**Client version**
5.0.0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - .NET: 7.0

**Additional context**

**Comment by MartinM85** [comment]
Maybe it can happen after update NuGet package from rc5 to 5.0.0.
After the cleanup and rebuild the solution there is no issue.
